name: 'Wait Vercel Mono Deployment'
description: 'GitHub Action that waits on multiple deployments of a PR and outputs their URLs'
branding:
    icon: 'clock'
    color: 'green'
inputs:
    actor_name:
        description: 'The name of the actor that will be used when checking for a new deployment'
        default: 'vercel[bot]'
        required: false
    github_token:
        description: 'The Github Secret'
        required: true
    vercel_password:
        description: 'Vercel password protection secret'
        required: false
    environment:
        description: 'The name of the environment that was deployed to (e.g., "Preview" or "Production")'
        required: false
    max_timeout:
        description: 'The timeout in seconds to be used when running each action step'
        default: '600'
        required: false
    allow_inactive_deployment:
        description: 'Use the most recent inactive deployment (previously deployed preview) associated with the pull request if no new deployment is available.'
        required: false
    path:
        description: 'The path to check. Defaults to the index of the domain'
        default: '/'
        required: false
    check_interval:
        description: 'How often in seconds should we make retry HTTP requests checking the deployment?'
        default: '2'
        required: false
    applications:
        description: 'Comma-separated list of application names to check for deployments. These application names should match the Vercel project name and GitHub Deplotments (eg. `my-app,my-app-staging`)'
        required: true
outputs:
    url:
        description: 'The fully qualified deploy preview URL'
    vercel_jwt:
        description: 'If the deployment is using password protection, this will be a JWT. Otherwise, outputs an empty string'
runs:
    using: 'node20'
    main: 'dist/index.js'
